name: Run Python Script Twice Daily (13:00 and 01:00 UTC)

on:
  schedule:
    - cron: "0 13,1 * * *"  # Runs at 13:00 UTC and 01:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - Check Directory Structure
        run: |
          echo "Current Directory:"
          pwd
          echo "List Files:"
          ls -lah

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install Playwright Browsers
        run: |
          playwright install chromium
          playwright install-deps

      - name: Create .env File
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}" >> .env
          echo "LLM_MODEL=${{ secrets.LLM_MODEL }}" >> .env
          cat .env  # Debugging - Check .env file

      - name: Debug - Confirm `crawl.py` Exists
        run: |
          ls -lah
          test -f crawl.py && echo "crawl.py found" || echo "crawl.py NOT FOUND"

      - name: Run Script
        run: python crawl.py
